"""Initn

Revision ID: 338129cca79a
Revises: 60d4416793ec
Create Date: 2025-03-17 02:20:41.553084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '338129cca79a'
down_revision: Union[str, None] = '60d4416793ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_key', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('private_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'private_key')
    op.drop_column('user', 'public_key')
    # ### end Alembic commands ###
