"""Add encrypted_aes_key

Revision ID: 066a7d66c7ff
Revises: 9da5b952242f
Create Date: 2026-01-21 20:55:30.728011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066a7d66c7ff'
down_revision = '9da5b952242f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_aes_key', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_note', schema=None) as batch_op:
        batch_op.drop_column('encrypted_aes_key')

    # ### end Alembic commands ###
