"""2fa zmiany

Revision ID: 2b0a9a4c807b
Revises: 066a7d66c7ff
Create Date: 2026-02-05 19:54:10.694209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0a9a4c807b'
down_revision = '066a7d66c7ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('content_html')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('totp_secret',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=500),
               nullable=False)
        batch_op.drop_column('is_2fa_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_2fa_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('totp_secret',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=32),
               nullable=True)

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content_html', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
