"""Update models

Revision ID: 9da5b952242f
Revises: cd0b5a6f5ec7
Create Date: 2026-01-20 18:18:36.778749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9da5b952242f'
down_revision = 'cd0b5a6f5ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_history')
    op.drop_table('signature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signature',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('signature', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('signed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], name='signature_note_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='signature_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='signature_pkey')
    )
    op.create_table('login_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('login_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='login_history_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='login_history_pkey')
    )
    # ### end Alembic commands ###
